### ISSUE TITLE
run module with its own variable

### ISSUE THREAD

**Issue by lguohan** [ansible-community/pytest-ansible#27]
I'd like to run following task, how can i achieve using pytest?

```
- name: Gather information from LLDP
  lldp:
  vars:
    ansible_shell_type: docker
    ansible_python_interpreter: docker exec -i lldp python
```
